version : "3"
services:
  database:
    image: mysql:5.7
    volumes:
      #- database_data:/d/Users/Cyprien/Documents/Github
      - database_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_blog
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: bloggy
      MYSQL_PASSWORD: bloggeur
      
  le_blog:
    depends_on:
      - database 
    image: ghost:latest
    ports: 
      - "8080:80"
    restart: always
    environment:
      NODE_ENV: production

volumes:
  database_data: {}