version: "3"
services:
  my_db:
    image: mysql:latest
    volumes:
      - my_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'standard_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'bigpassword'
      TZ: "America/Montreal"

  blog_online:
    depends_on:
      - my_db
    image: ghost:latest
    #image: my_ghost
    ports:
     - "8080:80"
    restart: always
    environment:
      NODE_ENV: development

volumes:
    my_data: {}